### ISSUE TITLE
AUTHENTICATION_FAILED: OAuth signatures did not match. Acceptable signature base string

### ISSUE THREAD

**Issue by imiten** [Mastercard/oauth1-signer-python#37]
Hi,

REF:
https://github.com/Mastercard/client-encryption-python/issues/11

Now I am trying delete api and get below error.  delete.sh updated it to pass payload file as arg to mc_oauth.py (also updated to use payload file name as arg) and uses delete api endpoint.

./delete.sh 
{
  "Errors": {
    "Error": [
      {
        "Source": "Gateway",
        "ReasonCode": "AUTHENTICATION_FAILED",
        "Description": "OAuth signatures did not match. Acceptable signature base string: POST&https%3A%2F%2Fsandbox.api.mastercard.com%2Fmdes%2Fdigitization%2Fstatic%2F1%2F0%2Fdelete&oauth_body_hash%3D5FDt0rM69jVreY5dwNJCGcrHeVDSe5tJuYQvFgDNElE%3D%26oauth_consumer_key%3Dwvy02aNQSjpjn3IEuFx_39Ew3mKD2I0e4qAGII_N9a062894%21833a8684c56e4abbb2bba5db3a1248550000000000000000%26oauth_nonce%3DO9WTR2xqUpBdSKVL%26oauth_signature_method%3DRSA-SHA256%26oauth_timestamp%3D1638619140%26oauth_version%3D1.0",
        "Recoverable": false,
        "Details": null
      }
    ]
  }
}

payload (from https://developer.mastercard.com/mdes-digital-enablement/documentation/api-reference/):
cat deletepayload.json 
{
  "responseHost": "site2.payment-app-provider.com",
  "requestId": 123456,
  "paymentAppInstanceId": 123456789,
  "tokenUniqueReferences": "DWSPMC000000000132d72d4fcb2f4136a0532d3093ff1a45",
  "causedBy": "CARDHOLDER",
  "reason": "Lost/stolen device",
  "reasonCode": "SUSPECTED_FRAUD"
}

**Comment by jaaufauvre** [comment]
Hi @imiten,

GitHub issues are only for reporting bugs or for opening feature requests.

As explained in https://github.com/Mastercard/client-encryption-python/issues/11, please try https://developer.mastercard.com/support. The support team should be able to assist you.

Also, next time you open a bug report or feature request, please use the provided templates:
![image](https://user-images.githubusercontent.com/3964455/144709627-47a7b7b2-9a8a-449d-b652-17dd56f454e8.png)
