### ISSUE TITLE
pyOpenSSL version doesn't support Cryptography 42.0.0

### ISSUE THREAD

**Issue by Rizzle93** [Mastercard/oauth1-signer-python#56]
Running pipdeptree after install of the mastercard oauth1-signer-python shows that this library is pinning the pyopenssl version meaning that cryptography 42.0.0 is not supported

mastercard-oauth1-signer==1.8.0
├── Deprecated [required: Any, installed: 1.2.14]
│   └── wrapt [required: >=1.10,<2, installed: 1.16.0]
├── pyOpenSSL [required: >=22.1.0,<=23.2.0, installed: 23.2.0]
│   └── cryptography [required: >=38.0.0,<42,!=40.0.1,!=40.0.0, installed: 41.0.7]
│       └── cffi [required: >=1.12, installed: 1.16.0]
│           └── pycparser [required: Any, installed: 2.21]

Issue seems to be on this line in setup.py: https://github.com/Mastercard/oauth1-signer-python/blob/main/setup.py#L49
Please update your library to support a minumum of pyOpenSSL 23.3.0 (so that Cryptography 42.0.0 can be installed)

**Comment by karen-avetisyan-mc** [comment]
Please use the latest version 1.9.0 and let us know if issue has been resolved
